name: ROS Humble Hawksbill

on:
  pull_request:
  push:
  workflow_dispatch:
    
jobs:
  test_humble:
    name: test_humble
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Test Humble
        uses: ./.github/actions/test_humble/

